<?php
session_start();
$pdo=new PDO('mysql:host=127.0.0.1;dbname=sql_pesonatari_site;charset=utf8mb4','sql_pesonatari_site','dcbf4afe83baa8',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));
if(isset($_GET['ajax'])&&$_GET['ajax']==='tari'){ $q='%'.trim($_GET['q']??'').'%';$st=$pdo->prepare('SELECT id,nama_tari,provinsi,kategori,gambar FROM tari WHERE nama_tari LIKE ? ORDER BY id DESC LIMIT 12');$st->execute([$q]);header('Content-Type: application/json');echo json_encode($st->fetchAll());exit; }
if($_SERVER['REQUEST_METHOD']==='POST' && !hash_equals($_SESSION['csrf'],$_POST['csrf']??''))exit('Invalid CSRF');
if(isset($_POST['vote'])){$pdo->prepare('INSERT INTO vote(tari_id,session_key) VALUES(?,?)')->execute([(int)$_POST['tari_id'],session_id()]);header('Location:index.php#vote');exit;}
if(isset($_POST['fav'])){$pdo->prepare('INSERT INTO favorit(tari_id,session_key) VALUES(?,?)')->execute([(int)$_POST['tari_id'],session_id()]);header('Location:index.php#tari');exit;}
$popular=$pdo->query('SELECT * FROM tari ORDER BY id DESC LIMIT 6')->fetchAll();
$events=$pdo->query('SELECT * FROM event ORDER BY tanggal ASC LIMIT 6')->fetchAll();
$votes=$pdo->query('SELECT t.nama_tari,COUNT(v.id) c FROM tari t LEFT JOIN vote v ON v.tari_id=t.id GROUP BY t.id ORDER BY c DESC LIMIT 5')->fetchAll();
?><!doctype html><html lang='id'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Langit Biru Nusantara</title>
<style>
:root{--bg:#041a35;--sky:#1f7fd6;--cyan:#42e6ff;--card:#ffffff12;--text:#eef8ff}*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;color:var(--text);background:#03162d}
.sky{position:fixed;inset:0;background:linear-gradient(180deg,#6dc5ff,#2a82d2,#f5a878,#03162d);background-size:100% 400%;animation:sky 32s linear infinite;z-index:-5}
.cloud{position:fixed;inset:0;background:radial-gradient(circle at 20% 20%,#fff3,transparent 27%),radial-gradient(circle at 80% 28%,#fff2,transparent 24%);filter:blur(10px);animation:cloud 35s linear infinite;z-index:-4}
.container{width:min(1160px,92%);margin:auto}.nav{position:sticky;top:0;z-index:50;background:#06264acc;backdrop-filter:blur(9px);border-bottom:1px solid #7de8ff3d}.navin{display:flex;justify-content:space-between;align-items:center;padding:16px 0}.menu a{color:#fff;text-decoration:none;margin-left:20px}
.hero{height:92vh;display:flex;align-items:center;position:relative}.hero:before{content:'';position:absolute;inset:0;background:radial-gradient(circle at 65% 35%,#57e8ff36,transparent 30%),linear-gradient(130deg,#0b3f76,#1d85b2)}
.hero .content{position:relative;max-width:760px}.title{font-size:4rem;margin:0}.sub{font-size:1.4rem;opacity:.95}.btn{display:inline-block;padding:12px 18px;border-radius:12px;text-decoration:none;margin-right:8px}.btn-c{background:var(--cyan);color:#00364f;font-weight:700}.btn-o{border:1px solid #bcf4ff;color:#fff}.card{background:var(--card);border:1px solid #82ebff4d;border-radius:16px;overflow:hidden;backdrop-filter:blur(5px)}
.section{padding:64px 0}.grid{display:grid;gap:16px}.g3{grid-template-columns:repeat(3,1fr)}.mapwrap{padding:22px}.map{width:100%;fill:#80d8ff;stroke:#0a467e;stroke-width:3}.prov{cursor:pointer;transition:.2s}.prov:hover{fill:#20c3ff;filter:drop-shadow(0 0 8px #41e7ff)}
input,select,textarea{width:100%;padding:11px;border-radius:10px;border:1px solid #8cefff55;background:#0d2f51;color:#fff}img{width:100%;height:210px;object-fit:cover}.tabs{display:flex;gap:8px;flex-wrap:wrap}.tabs button{padding:10px 14px;border-radius:999px;border:1px solid #7de8ff55;background:#0b3f71;color:#e6fbff}.tabs button.active{background:#2dd8ff;color:#00394f}
.reveal{opacity:0;transform:translateY(24px);transition:.7s}.reveal.show{opacity:1;transform:none}@media(max-width:900px){.g3{grid-template-columns:1fr}.title{font-size:2.4rem}}
@keyframes sky{0%{background-position:0 0}100%{background-position:0 100%}}@keyframes cloud{from{transform:translateX(0)}to{transform:translateX(-110px)}}
</style></head><body><div class='sky'></div><div class='cloud'></div>
<header class='nav'><div class='container navin'><h2>Langit Biru Nusantara</h2><nav class='menu'><a href='#tari'>Tari</a><a href='#event'>Festival</a><a href='tiket.php'>Tiket</a></nav></div></header>
<section class='hero'><div class='container content'><h1 class='title'>Hari Tari Nasional Indonesia</h1><p class='sub'>Portal budaya digital nasional yang cinematic, modern, dan interaktif.</p><a class='btn btn-c' href='#tari'>Jelajahi Tari</a><a class='btn btn-o' href='#event'>Lihat Festival</a><a class='btn btn-o' href='tiket.php'>Pesan Tiket</a></div></section>
<section class='section'><div class='container card' style='padding:14px'>Countdown: <b id='cd' data-date='2026-11-20'></b></div></section>
<section id='tari' class='section reveal'><div class='container'><h2>Tari Populer</h2><input id='search' placeholder='Cari tari...'><div id='tariList' class='grid g3' style='margin-top:16px'><?php foreach($popular as $t):?><article class='card'><img loading='lazy' src='<?=htmlspecialchars($t['gambar'])?>'><div style='padding:14px'><h3><?=$t['nama_tari']?></h3><small><?=$t['provinsi']?> • <?=$t['kategori']?></small><form method='post' style='margin-top:8px'><input type='hidden' name='csrf' value='<?=$_SESSION['csrf']?>'><input type='hidden' name='tari_id' value='<?=$t['id']?>'><button name='fav' class='btn btn-o'>Favorit</button></form></div></article><?php endforeach;?></div></div></section>
<section class='section reveal'><div class='container'><h2>Peta Indonesia Interaktif</h2><div class='card mapwrap'><svg viewBox='0 0 1200 430' class='map'><g class='prov' data-name='Sumatera'><path d='M70 190 L120 150 L180 160 L220 200 L190 245 L120 255 Z'/></g><g class='prov' data-name='Jawa'><path d='M280 325 L530 315 L580 328 L295 342 Z'/></g><g class='prov' data-name='Bali-Nusa'><path d='M595 330 L675 334 L705 344 L610 347 Z'/></g><g class='prov' data-name='Kalimantan'><path d='M430 150 L560 130 L655 180 L635 270 L510 285 L430 240 Z'/></g><g class='prov' data-name='Sulawesi'><path d='M735 145 L805 170 L780 210 L840 235 L810 278 L730 245 L760 185 Z'/></g><g class='prov' data-name='Maluku'><path d='M895 230 L950 215 L985 238 L930 270 Z'/></g><g class='prov' data-name='Papua'><path d='M995 200 L1130 188 L1180 236 L1040 290 L975 252 Z'/></g></svg><div id='mapInfo' class='card' style='padding:12px;margin-top:10px'>Klik pulau untuk melihat insight budaya.</div></div></div></section>
<section id='event' class='section reveal'><div class='container'><h2>Festival Budaya</h2><div class='grid g3'><?php foreach($events as $e):?><article class='card'><img loading='lazy' src='<?=htmlspecialchars($e['poster'])?>'><div style='padding:14px'><h3><?=$e['nama_event']?></h3><p><?=$e['lokasi']?> | <?=$e['tanggal']?></p><a class='btn btn-c' href='tiket.php?event_id=<?=$e['id']?>'>Order Tiket</a></div></article><?php endforeach;?></div></div></section>
<section id='vote' class='section reveal'><div class='container'><h2>Top Vote Budaya</h2><div class='grid g3'><?php foreach($votes as $v):?><div class='card' style='padding:14px'><b><?=$v['nama_tari']?></b><div><?=$v['c']?> vote</div></div><?php endforeach;?></div></div></section>
<section class='section reveal'><div class='container'><h2>Jelajahi Nusantara</h2><div class='tabs' id='tabs'><button data-r='Sumatera' class='active'>Sumatera</button><button data-r='Jawa'>Jawa</button><button data-r='Kalimantan'>Kalimantan</button><button data-r='Sulawesi'>Sulawesi</button><button data-r='Bali'>Bali</button><button data-r='Papua'>Papua</button></div><div id='preview' class='card' style='padding:16px;margin-top:12px'></div></div></section>
<script>
const cd=document.getElementById('cd');setInterval(()=>{const d=new Date(cd.dataset.date)-new Date();cd.textContent=d<=0?'Hari Tari Nasional dimulai!':Math.floor(d/86400000)+' hari '+Math.floor((d%86400000)/3600000)+' jam'},1000);
document.querySelectorAll('.prov').forEach(p=>p.onclick=()=>mapInfo.textContent='Pulau '+p.dataset.name+': tampilkan tari khas, festival, dan statistik mingguan.');
const data={Sumatera:['Tari Saman & Piring','Gerak kolektif dan energi adat'],Jawa:['Tari Serimpi','Elegan, filosofis, berakar keraton'],Kalimantan:['Tari Hudoq','Ritual Dayak penuh makna'],Sulawesi:['Tari Pakarena','Lembut dan sakral'],Bali:['Tari Kecak','Dramatik vokal cak'],Papua:['Tari Yospan','Persaudaraan dan sukacita']};
function paint(r){preview.innerHTML=`<h3>${r}</h3><p>${data[r][0]}</p><p>${data[r][1]}</p><a href='#tari' class='btn btn-c'>Lihat Detail Tari</a>`;}paint('Sumatera');document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');paint(b.dataset.r);});
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('show')), {threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));
search?.addEventListener('input',async()=>{const r=await fetch('index.php?ajax=tari&q='+encodeURIComponent(search.value));const d=await r.json();tariList.innerHTML=d.map(x=>`<article class='card'><img src='${x.gambar}'><div style='padding:14px'><h3>${x.nama_tari}</h3><small>${x.provinsi} • ${x.kategori}</small></div></article>`).join('')})
</script></body></html>
