<?php
session_start();
$pdo=new PDO('mysql:host=127.0.0.1;dbname=sql_pesonatari_site;charset=utf8mb4','sql_pesonatari_site','dcbf4afe83baa8',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));
$githubUrl='https://github.com/yourusername';
if(isset($_GET['ajax'])&&$_GET['ajax']==='tari'){ $q='%'.trim($_GET['q']??'').'%';$st=$pdo->prepare('SELECT id,nama_tari,provinsi,kategori,gambar FROM tari WHERE nama_tari LIKE ? ORDER BY id DESC LIMIT 12');$st->execute([$q]);header('Content-Type: application/json');echo json_encode($st->fetchAll());exit; }
$popular=$pdo->query('SELECT * FROM tari ORDER BY id DESC LIMIT 6')->fetchAll();$events=$pdo->query('SELECT * FROM event ORDER BY tanggal ASC LIMIT 6')->fetchAll();
?><!doctype html><html lang='id'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Langit Biru Nusantara</title><link rel='stylesheet' href='assets/style.css'></head><body class='batik'><div class='sky'></div><div class='cloud'></div>
<header class='nav'><div class='container navin'><h2>Langit Biru Nusantara</h2><nav class='menu'><a href='#tari'>Tari</a><a href='#peta'>Peta</a><a href='tiket.php'>Tiket</a></nav></div></header>
<section class='section'><div class='container glass'><div style='padding:16px'><h3>Portal Resmi Hari Tari Nasional Indonesia</h3><p>Selamat datang di pusat informasi budaya, festival, dan tiket resmi Langit Biru Nusantara.</p></div></div></section>
<section class='hero'><div class='container hero-grid'><div><h1>Hari Tari Nasional Indonesia</h1><p>Festival budaya digital nasional dalam nuansa langit biru Nusantara.</p><a class='btn btn-c' href='#tari'>Jelajahi Tari</a><a class='btn' href='#event'>Lihat Festival</a><a class='btn' href='tiket.php'>Pesan Tiket</a><div class='glass' style='padding:12px;margin-top:14px'>Countdown: <b id='cd' data-date='2026-11-20'></b></div></div><div class='glass' style='padding:10px'><iframe style='width:100%;height:300px;border:0;border-radius:12px' src='https://www.youtube.com/embed/oqQeB9cIps4?autoplay=1&mute=1&loop=1&playlist=oqQeB9cIps4&controls=1' allow='autoplay; encrypted-media'></iframe></div></div></section>
<section id='tari' class='section reveal'><div class='container'><h2>Tari Populer</h2><input id='search' placeholder='Cari tari...'><div id='tariList' class='grid g3' style='margin-top:14px'><?php foreach($popular as $t):?><article class='card'><img loading='lazy' src='<?=htmlspecialchars($t['gambar'])?>'><div style='padding:14px'><h3><?=$t['nama_tari']?></h3><small><?=$t['provinsi']?> • <?=$t['kategori']?></small></div></article><?php endforeach;?></div></div></section>
<section id='peta' class='section reveal'><div class='container'><h2>Peta Budaya (Google Map)</h2><div class='card map-shell'><iframe class='map-embed' loading='lazy' src='https://maps.google.com/maps?q=Indonesia&t=k&z=4&ie=UTF8&iwloc=&output=embed'></iframe><div class='dots'><button class='dot' data-i='sumatera'>● Sumatera</button><button class='dot' data-i='jawa'>● Jawa</button><button class='dot' data-i='kalimantan'>● Kalimantan</button><button class='dot' data-i='sulawesi'>● Sulawesi</button><button class='dot' data-i='bali'>● Bali</button><button class='dot' data-i='papua'>● Papua</button></div><div id='mapInfo' class='card info'>Klik titik pulau untuk menampilkan informasi budaya dan tarian.</div></div></div></section>
<section id='event' class='section reveal'><div class='container'><h2>Event Festival</h2><div class='grid g3'><?php foreach($events as $e):?><article class='card'><img src='<?=htmlspecialchars($e['poster'])?>'><div style='padding:14px'><h3><?=$e['nama_event']?></h3><p><?=$e['lokasi']?> | <?=$e['tanggal']?></p><a class='btn btn-c' href='tiket.php?event_id=<?=$e['id']?>'>Order Tiket</a></div></article><?php endforeach;?></div></div></section>
<footer class='section'><div class='container'><div class='card' style='padding:18px'><h3>Sponsor Festival</h3><div class='grid g3'><div class='card' style='padding:12px'>Kementerian Kebudayaan RI</div><div class='card' style='padding:12px'>Indonesia Creative Hub</div><div class='card' style='padding:12px'>Nusantara Art Foundation</div></div><hr style='border-color:#8cefff44;margin:16px 0'><p>Ikuti update source code: <a href='<?=$githubUrl?>' target='_blank' style='color:#7befff'><?=$githubUrl?></a></p><small>© 2026 Langit Biru Nusantara</small></div></div></footer><script src='assets/app.js' defer></script></body></html>
