<?php
session_start();
$pdo=new PDO('mysql:host=127.0.0.1;dbname=sql_pesonatari_site;charset=utf8mb4','sql_pesonatari_site','dcbf4afe83baa8',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));
if(isset($_GET['ajax'])&&$_GET['ajax']==='tari'){ $q='%'.trim($_GET['q']??'').'%';$st=$pdo->prepare('SELECT id,nama_tari,provinsi,kategori,gambar FROM tari WHERE nama_tari LIKE ? ORDER BY id DESC LIMIT 12');$st->execute([$q]);header('Content-Type: application/json');echo json_encode($st->fetchAll());exit; }
if($_SERVER['REQUEST_METHOD']==='POST' && !hash_equals($_SESSION['csrf'],$_POST['csrf']??''))exit('Invalid CSRF');
if(isset($_POST['vote'])){$pdo->prepare('INSERT INTO vote(tari_id,session_key) VALUES(?,?)')->execute([(int)$_POST['tari_id'],session_id()]);header('Location:index.php#vote');exit;}
if(isset($_POST['fav'])){$pdo->prepare('INSERT INTO favorit(tari_id,session_key) VALUES(?,?)')->execute([(int)$_POST['tari_id'],session_id()]);header('Location:index.php#tari');exit;}
$popular=$pdo->query('SELECT * FROM tari ORDER BY id DESC LIMIT 6')->fetchAll();
$events=$pdo->query('SELECT * FROM event ORDER BY tanggal ASC LIMIT 6')->fetchAll();
$votes=$pdo->query('SELECT t.nama_tari,COUNT(v.id) c FROM tari t LEFT JOIN vote v ON v.tari_id=t.id GROUP BY t.id ORDER BY c DESC LIMIT 5')->fetchAll();
?><!doctype html><html lang='id'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Langit Biru Nusantara</title>
<link rel='stylesheet' href='assets/style.css'></head><body><div class='sky'></div><div class='cloud'></div>
<header class='nav'><div class='container navin'><h2>Langit Biru Nusantara</h2><nav class='menu'><a href='#tari'>Tari</a><a href='#event'>Festival</a><a href='tiket.php'>Tiket</a></nav></div></header>
<section class='hero'><div class='container content'><h1 class='title'>Hari Tari Nasional Indonesia</h1><p class='sub'>Portal budaya digital nasional yang cinematic, modern, dan interaktif.</p><a class='btn btn-c' href='#tari'>Jelajahi Tari</a><a class='btn btn-o' href='#event'>Lihat Festival</a><a class='btn btn-o' href='tiket.php'>Pesan Tiket</a></div></section>
<section class='section'><div class='container card' style='padding:14px'>Countdown: <b id='cd' data-date='2026-11-20'></b></div></section>
<section id='tari' class='section reveal'><div class='container'><h2>Tari Populer</h2><input id='search' placeholder='Cari tari...'><div id='tariList' class='grid g3' style='margin-top:16px'><?php foreach($popular as $t):?><article class='card'><img loading='lazy' src='<?=htmlspecialchars($t['gambar'])?>'><div style='padding:14px'><h3><?=$t['nama_tari']?></h3><small><?=$t['provinsi']?> • <?=$t['kategori']?></small><form method='post' style='margin-top:8px'><input type='hidden' name='csrf' value='<?=$_SESSION['csrf']?>'><input type='hidden' name='tari_id' value='<?=$t['id']?>'><button name='fav' class='btn btn-o'>Favorit</button></form></div></article><?php endforeach;?></div></div></section>
<section class='section reveal'><div class='container'><h2>Peta Indonesia Interaktif</h2><div class='card mapwrap'><svg viewBox='0 0 1200 430' class='map'><g class='prov' data-name='Sumatera'><path d='M70 190 L120 150 L180 160 L220 200 L190 245 L120 255 Z'/></g><g class='prov' data-name='Jawa'><path d='M280 325 L530 315 L580 328 L295 342 Z'/></g><g class='prov' data-name='Bali-Nusa'><path d='M595 330 L675 334 L705 344 L610 347 Z'/></g><g class='prov' data-name='Kalimantan'><path d='M430 150 L560 130 L655 180 L635 270 L510 285 L430 240 Z'/></g><g class='prov' data-name='Sulawesi'><path d='M735 145 L805 170 L780 210 L840 235 L810 278 L730 245 L760 185 Z'/></g><g class='prov' data-name='Maluku'><path d='M895 230 L950 215 L985 238 L930 270 Z'/></g><g class='prov' data-name='Papua'><path d='M995 200 L1130 188 L1180 236 L1040 290 L975 252 Z'/></g></svg><div id='mapInfo' class='card' style='padding:12px;margin-top:10px'>Klik pulau untuk melihat insight budaya.</div></div></div></section>
<section id='event' class='section reveal'><div class='container'><h2>Festival Budaya</h2><div class='grid g3'><?php foreach($events as $e):?><article class='card'><img loading='lazy' src='<?=htmlspecialchars($e['poster'])?>'><div style='padding:14px'><h3><?=$e['nama_event']?></h3><p><?=$e['lokasi']?> | <?=$e['tanggal']?></p><a class='btn btn-c' href='tiket.php?event_id=<?=$e['id']?>'>Order Tiket</a></div></article><?php endforeach;?></div></div></section>
<section id='vote' class='section reveal'><div class='container'><h2>Top Vote Budaya</h2><div class='grid g3'><?php foreach($votes as $v):?><div class='card' style='padding:14px'><b><?=$v['nama_tari']?></b><div><?=$v['c']?> vote</div></div><?php endforeach;?></div></div></section>
<section class='section reveal'><div class='container'><h2>Jelajahi Nusantara</h2><div class='tabs' id='tabs'><button data-r='Sumatera' class='active'>Sumatera</button><button data-r='Jawa'>Jawa</button><button data-r='Kalimantan'>Kalimantan</button><button data-r='Sulawesi'>Sulawesi</button><button data-r='Bali'>Bali</button><button data-r='Papua'>Papua</button></div><div id='preview' class='card' style='padding:16px;margin-top:12px'></div></div></section>
<script src='assets/app.js' defer></script></body></html>
