<?php
session_start();
$pdo=new PDO('mysql:host=127.0.0.1;dbname=sql_pesonatari_site;charset=utf8mb4','sql_pesonatari_site','dcbf4afe83baa8',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));
if($_SERVER['REQUEST_METHOD']==='POST' && hash_equals($_SESSION['csrf'],$_POST['csrf']??'')){$tot=(int)$_POST['jumlah']*(int)$_POST['harga'];$pdo->prepare('INSERT INTO tiket(event_id,nama,email,jumlah,total_harga,status) VALUES(?,?,?,?,?,?)')->execute([(int)$_POST['event_id'],$_POST['nama'],$_POST['email'],(int)$_POST['jumlah'],$tot,'pending']);header('Location:tiket.php?ok=1');exit;}
$events=$pdo->query('SELECT * FROM event ORDER BY tanggal ASC')->fetchAll();
?><!doctype html><html lang='id'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Order Tiket Festival</title><link rel='stylesheet' href='assets/tiket.css'></head><body>
<header class='top'><div class='wrap topin'><h1>Order Tiket Festival</h1><a class='btn' href='index.php'>← Kembali ke Beranda</a></div></header>
<section class='hero'><div class='wrap'><?php if(isset($_GET['ok'])): ?><div class='notice'>Pesanan berhasil dikirim. Silakan lanjutkan proses pembayaran dan tunggu verifikasi admin.</div><?php endif; ?><div class='grid'><?php foreach($events as $i=>$e): $img=htmlspecialchars($e['poster']); ?><article class='ticket-card'><div class='banner' style="background-image:url('<?=$img?>')"></div><div class='content'><h3><?=htmlspecialchars($e['nama_event'])?></h3><p class='meta'><?=htmlspecialchars($e['lokasi'])?> • <?=htmlspecialchars($e['tanggal'])?></p><div class='price'>Rp<?=number_format($e['harga_tiket'])?> / tiket</div><form method='post'><input type='hidden' name='csrf' value='<?=$_SESSION['csrf']?>'><input type='hidden' name='event_id' value='<?=$e['id']?>'><input type='hidden' name='harga' value='<?=$e['harga_tiket']?>'><label>Nama Lengkap</label><input name='nama' required placeholder='Masukkan nama lengkap'><label>Email Aktif</label><input name='email' type='email' required placeholder='Masukkan email aktif'><label>Jumlah Tiket</label><input type='number' name='jumlah' min='1' value='1' required><div class='actions'><button class='btn primary' type='submit'>Pesan Sekarang</button><small>Total otomatis dihitung saat submit</small></div></form></div></article><?php endforeach;?></div><div class='legend'><b>Info:</b> Setelah order, data masuk ke sistem tiket dengan status <i>pending</i>. Lanjutkan ke pembayaran sesuai instruksi admin.</div></div></section>
</body></html>
