<?php
require_once __DIR__.'/../app/config/database.php';require_once __DIR__.'/../app/helpers/common.php';verify_csrf();$db=pdo_db();$r=$_GET['r']??'home';
if($r==='tari_ajax'){ $q='%'.trim($_GET['q']??'').'%';$st=$db->prepare('SELECT id,nama_tari,provinsi,kategori,gambar FROM tari WHERE nama_tari LIKE ? ORDER BY id DESC LIMIT 12');$st->execute([$q]);header('Content-Type: application/json');echo json_encode($st->fetchAll());exit; }
if($r==='vote'&&$_SERVER['REQUEST_METHOD']==='POST'){ $db->prepare('INSERT INTO vote(tari_id,session_key) VALUES(?,?)')->execute([(int)$_POST['tari_id'],session_id()]);header('Location:?r=home#vote');exit; }
if($r==='checkout'&&$_SERVER['REQUEST_METHOD']==='POST'){ $tot=(int)$_POST['jumlah']*(int)$_POST['harga_tiket'];$db->prepare('INSERT INTO tiket(event_id,nama,email,jumlah,total_harga,status) VALUES(?,?,?,?,?,?)')->execute([(int)$_POST['event_id'],trim($_POST['nama']),trim($_POST['email']),(int)$_POST['jumlah'],$tot,'pending']);header('Location:?r=payment&id='.$db->lastInsertId());exit; }
if($r==='payment_submit'&&$_SERVER['REQUEST_METHOD']==='POST'){ $id=(int)$_GET['id'];$b=upimg('bukti','bukti');$db->prepare('INSERT INTO pembayaran(tiket_id,metode,bukti,status) VALUES(?,?,?,?)')->execute([$id,$_POST['metode'],$b,'menunggu']);$db->prepare("UPDATE tiket SET status='menunggu verifikasi' WHERE id=?")->execute([$id]);header('Location:?r=payment&id='.$id.'&ok=1');exit; }
if($r==='admin_tari_add'&&$_SERVER['REQUEST_METHOD']==='POST'){ $g=upimg('gambar','tari');$db->prepare('INSERT INTO tari(nama_tari,daerah,provinsi,kategori,deskripsi,sejarah,filosofi,properti_tari,pakaian_adat,alat_musik,video_url,gambar,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,NOW())')->execute([$_POST['nama_tari'],$_POST['daerah'],$_POST['provinsi'],$_POST['kategori'],$_POST['deskripsi'],$_POST['sejarah'],$_POST['filosofi'],$_POST['properti_tari'],$_POST['pakaian_adat'],$_POST['alat_musik'],$_POST['video_url'],$g]);header('Location:?r=admin&tari=1');exit; }
if($r==='admin_event_add'&&$_SERVER['REQUEST_METHOD']==='POST'){ $p=upimg('poster','event');$db->prepare('INSERT INTO event(nama_event,lokasi,tanggal,harga_tiket,kuota,deskripsi,poster) VALUES(?,?,?,?,?,?,?)')->execute([$_POST['nama_event'],$_POST['lokasi'],$_POST['tanggal'],(int)$_POST['harga_tiket'],(int)$_POST['kuota'],$_POST['deskripsi'],$p]);header('Location:?r=admin&event=1');exit; }
$popular=$db->query('SELECT * FROM tari ORDER BY id DESC LIMIT 6')->fetchAll();$events=$db->query('SELECT * FROM event ORDER BY tanggal ASC LIMIT 6')->fetchAll();$vote=$db->query('SELECT t.id,t.nama_tari,COUNT(v.id) vc FROM tari t LEFT JOIN vote v ON v.tari_id=t.id GROUP BY t.id ORDER BY vc DESC LIMIT 5')->fetchAll();
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=APP_NAME?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="assets/css/app.min.css"></head><body>
<nav class="navbar navbar-expand-lg fixed-top nav-glass"><div class="container"><a class="navbar-brand text-white" href="?r=home">Langit Biru Nusantara</a><div class="navbar-nav ms-auto"><a class="nav-link text-white" href="#tari">Tari</a><a class="nav-link text-white" href="#event">Festival</a><a class="nav-link text-white" href="?r=admin">Admin</a></div></div></nav>
<section class="hero"><iframe src="https://www.youtube.com/embed/x8Kzn9x0j4c?autoplay=1&mute=1&loop=1&playlist=x8Kzn9x0j4c&controls=0" allow="autoplay"></iframe><div class="overlay"></div><div class="container hero-content"><h1>Hari Tari Nasional Indonesia</h1><p>Gerakan Nusantara Untuk Masa Depan Budaya Indonesia</p><a href="#tari" class="btn btn-cyan">Jelajahi Tari</a><a href="#event" class="btn btn-outline-light">Lihat Festival</a><a href="#event" class="btn btn-light">Pesan Tiket</a></div></section>
<div class="container py-5"><div class="countdown">Countdown: <b id="cd" data-date="2026-11-20"></b></div></div>
<section id="tari" class="container py-5"><h2>Tari Populer</h2><input id="search" class="form-control my-3" placeholder="Cari tari"><div id="tari-list" class="row"><?php foreach($popular as $t):?><div class="col-md-4"><div class="card sky mb-3"><img loading="lazy" src="<?=esc($t['gambar'])?>" class="card-img-top"><div class="card-body"><h5><?=esc($t['nama_tari'])?></h5><small><?=esc($t['provinsi'])?> • <?=esc($t['kategori'])?></small></div></div></div><?php endforeach;?></div></section>
<section class="container py-5"><h2>Peta Indonesia Interaktif</h2><svg viewBox="0 0 320 130" class="map"><rect class="prov" data-name="Sumatera" x="10" y="40" width="70" height="22"/><rect class="prov" data-name="Jawa" x="95" y="72" width="56" height="12"/><rect class="prov" data-name="Kalimantan" x="130" y="35" width="62" height="28"/><rect class="prov" data-name="Sulawesi" x="205" y="34" width="40" height="30"/><rect class="prov" data-name="Papua" x="255" y="45" width="55" height="22"/></svg><div id="map-info" class="alert alert-info mt-3">Klik provinsi untuk melihat tari khas.</div></section>
<section id="event" class="container py-5"><h2>Event Festival</h2><div class="row"><?php foreach($events as $e):?><div class="col-md-4"><div class="card sky mb-3"><img loading="lazy" src="<?=esc($e['poster'])?>" class="card-img-top"><div class="card-body"><h5><?=esc($e['nama_event'])?></h5><p><?=esc($e['lokasi'])?> | <?=esc($e['tanggal'])?></p><form method="post" action="?r=checkout"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="event_id" value="<?=$e['id']?>"><input type="hidden" name="harga_tiket" value="<?=$e['harga_tiket']?>"><input required name="nama" class="form-control mb-2" placeholder="Nama"><input required name="email" class="form-control mb-2" placeholder="Email"><input name="jumlah" type="number" min="1" value="1" class="form-control mb-2"><button class="btn btn-cyan w-100">Pesan Tiket</button></form></div></div></div><?php endforeach;?></div></section>
<section id="vote" class="container py-5"><h2>Top Vote Tari</h2><?php foreach($vote as $v):?><form method="post" action="?r=vote" class="vote-row"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="tari_id" value="<?=$v['id']?>"><span><?=esc($v['nama_tari'])?> (<?=$v['vc']?>)</span><button class="btn btn-sm btn-cyan">Vote</button></form><?php endforeach;?></section>
<?php if($r==='payment'){ $id=(int)($_GET['id']??0);$st=$db->prepare('SELECT t.*,e.nama_event FROM tiket t JOIN event e ON e.id=t.event_id WHERE t.id=?');$st->execute([$id]);$trx=$st->fetch(); ?><section class="container py-5"><h2>Pembayaran</h2><p><?=esc($trx['nama_event'])?> - Rp<?=number_format($trx['total_harga'])?></p><img loading="lazy" src="https://api.qrserver.com/v1/create-qr-code/?size=190x190&data=QRIS-DUMMY-LANGIT-BIRU" width="190"><form method="post" action="?r=payment_submit&id=<?=$id?>" enctype="multipart/form-data" class="mt-3"><input type="hidden" name="csrf" value="<?=csrf()?>"><select name="metode" class="form-select mb-2"><option>QRIS dummy</option><option>Transfer bank</option><option>E-wallet dummy</option></select><input type="file" name="bukti" class="form-control mb-2" required><button class="btn btn-cyan">Upload bukti</button></form><?php if(isset($_GET['ok']))echo '<div class="alert alert-success mt-2">Status: menunggu verifikasi</div>';?></section><?php } ?>
<?php if($r==='admin'){ ?><section class="container py-5"><h2>Admin Dashboard</h2><div class="admin-grid"><aside><ul><li>Dashboard</li><li>Kelola Tari</li><li>Kelola Event</li><li>Kelola Tiket</li><li>User</li><li>Logout</li></ul></aside><main><h5>Tambah Tari</h5><form method="post" action="?r=admin_tari_add" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=csrf()?>"><input name="nama_tari" class="form-control mb-2" required placeholder="nama_tari"><input name="daerah" class="form-control mb-2" required><input name="provinsi" class="form-control mb-2" required><input name="kategori" class="form-control mb-2" required><textarea name="deskripsi" class="form-control mb-2" required></textarea><textarea name="sejarah" class="form-control mb-2" required></textarea><textarea name="filosofi" class="form-control mb-2" required></textarea><input name="properti_tari" class="form-control mb-2" required><input name="pakaian_adat" class="form-control mb-2" required><input name="alat_musik" class="form-control mb-2" required><input name="video_url" class="form-control mb-2" required><input type="file" name="gambar" class="form-control mb-2"><button class="btn btn-cyan">Simpan Tari</button></form><hr><h5>Tambah Event</h5><form method="post" action="?r=admin_event_add" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=csrf()?>"><input name="nama_event" class="form-control mb-2" required><input name="lokasi" class="form-control mb-2" required><input type="date" name="tanggal" class="form-control mb-2" required><input type="number" name="harga_tiket" class="form-control mb-2" required><input type="number" name="kuota" class="form-control mb-2" required><textarea name="deskripsi" class="form-control mb-2" required></textarea><input type="file" name="poster" class="form-control mb-2"><button class="btn btn-cyan">Simpan Event</button></form></main></div></section><?php } ?>
<footer class="py-5 text-center text-white">© 2026 Langit Biru Nusantara</footer><script src="assets/js/app.min.js" defer></script></body></html>
