CREATE DATABASE IF NOT EXISTS sql_pesonatari_site CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sql_pesonatari_site;
CREATE TABLE tari(id INT AUTO_INCREMENT PRIMARY KEY,nama_tari VARCHAR(120) NOT NULL,daerah VARCHAR(120) NOT NULL,provinsi VARCHAR(120) NOT NULL,kategori VARCHAR(80) NOT NULL,deskripsi TEXT NOT NULL,sejarah TEXT NOT NULL,filosofi TEXT NOT NULL,properti_tari VARCHAR(180) NOT NULL,pakaian_adat VARCHAR(180) NOT NULL,alat_musik VARCHAR(180) NOT NULL,video_url VARCHAR(255) NOT NULL,gambar VARCHAR(255) NOT NULL,created_at DATETIME NOT NULL,INDEX idx_nama(nama_tari),INDEX idx_kategori(kategori),INDEX idx_provinsi(provinsi));
CREATE TABLE event(id INT AUTO_INCREMENT PRIMARY KEY,nama_event VARCHAR(150) NOT NULL,lokasi VARCHAR(150) NOT NULL,tanggal DATE NOT NULL,harga_tiket INT NOT NULL,kuota INT NOT NULL,deskripsi TEXT NOT NULL,poster VARCHAR(255) NOT NULL,INDEX idx_tanggal(tanggal));
CREATE TABLE tiket(id INT AUTO_INCREMENT PRIMARY KEY,event_id INT NOT NULL,nama VARCHAR(120) NOT NULL,email VARCHAR(120) NOT NULL,jumlah INT NOT NULL,total_harga INT NOT NULL,status VARCHAR(50) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(event_id) REFERENCES event(id) ON DELETE CASCADE,INDEX idx_event(event_id));
CREATE TABLE pembayaran(id INT AUTO_INCREMENT PRIMARY KEY,tiket_id INT NOT NULL,metode VARCHAR(40) NOT NULL,bukti VARCHAR(255),status VARCHAR(50) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(tiket_id) REFERENCES tiket(id) ON DELETE CASCADE);
CREATE TABLE vote(id INT AUTO_INCREMENT PRIMARY KEY,tari_id INT NOT NULL,session_key VARCHAR(128) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(tari_id) REFERENCES tari(id) ON DELETE CASCADE,INDEX idx_tari_vote(tari_id));
CREATE TABLE komentar(id INT AUTO_INCREMENT PRIMARY KEY,tari_id INT NOT NULL,nama VARCHAR(120) NOT NULL,isi TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(tari_id) REFERENCES tari(id) ON DELETE CASCADE);
CREATE TABLE favorit(id INT AUTO_INCREMENT PRIMARY KEY,tari_id INT NOT NULL,session_key VARCHAR(128) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(tari_id) REFERENCES tari(id) ON DELETE CASCADE,INDEX idx_fav(tari_id));
INSERT INTO tari(nama_tari,daerah,provinsi,kategori,deskripsi,sejarah,filosofi,properti_tari,pakaian_adat,alat_musik,video_url,gambar,created_at) VALUES
('Tari Saman','Gayo Lues','Aceh','Tradisional','Tarian sinkron penuh energi dari Aceh untuk perayaan budaya.','Berasal dari tradisi dakwah dan pendidikan masyarakat Gayo.','Merefleksikan persatuan, disiplin, dan semangat gotong royong.','Alas duduk','Busana kerawang Gayo','Tepuk tangan dan vokal','https://www.youtube.com/watch?v=0R2f4b7HfVw','https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=70',NOW()),
('Tari Kecak','Ubud','Bali','Pertunjukan','Tarian drama kolosal dengan paduan suara cak khas Bali.','Dikembangkan sebagai pertunjukan wisata budaya sejak abad 20.','Melambangkan kolaborasi, keseimbangan, dan nilai spiritual.','Obor','Kain poleng','Vokal cak','https://www.youtube.com/watch?v=I5xN1v9jv4Q','https://images.unsplash.com/photo-1533907650686-70576141c030?auto=format&fit=crop&w=800&q=70',NOW());
INSERT INTO event(nama_event,lokasi,tanggal,harga_tiket,kuota,deskripsi,poster) VALUES
('Festival Langit Biru Nusantara 2026','Taman Ismail Marzuki, Jakarta','2026-11-20',150000,500,'Festival tari modern-cultural dengan panggung sinematik dan kolaborasi lintas provinsi.','https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=70');
